prefix = /usr/local
cfgdir = ${prefix}/lib/qrouter

install:
	mkdir -p ${cfgdir}
	cp *.cfg ${cfgdir}

clean:
	echo "Nothing to do in lib for make clean"

veryclean:
	echo "Nothing to do in lib for make veryclean"

distclean:
	echo "Nothing to do in lib for make distclean"
